agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_03_18

env:
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "initialize"
    key: "initialize"
    command:
      - echo "--- Instantiate project"
      - julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'

      - echo "--- Instantiate test"
      - julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'
    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: ":computer: unit tests"
    key: "cpu_unittests"
    command:
      - "julia --project=test --color=yes test/aerosol_activation_emulators.jl"

  - wait

  - label: ":envelope: Slack report"
    command: |
        if [[ ${{ steps.cpu_unittests.exit_code }} -eq 0 ]]; then
          slack-upload -c "#microphysics-dev" -x "CM.jl longruns success"
        else
          slack-upload -c "#microphysics-dev" -x "CM.jl longruns failure :("
        fi
